# Application name
spring.application.name=notifier

# Active profile (override with -Dspring.profiles.active=local)
spring.profiles.active=local

# JPA
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration

# Include error messages in HTTP responses
server.error.include-message=always

# Retry configuration
retry.max-attempts=4
retry.backoff-delay=2000

# SQS consumer config
aws.sqs.listener.executor.pool.size=45
aws.sqs.listener.executor.queue.capacity=100
aws.sqs.consumer.event-notifications.maxConcurrentMessage=5
aws.sqs.consumer.event-notifications.maxMessagesPerPoll=5
aws.sqs.consumer.event-notifications.pollTimeoutSeconds=20
