# H2 in-memory database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:notifierdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=cobre
spring.datasource.password=cobre1234

# LocalStack
spring.cloud.aws.credentials.sts.role-arn=arn:aws:iam::000000000000:role/local_role
spring.cloud.aws.region.static=eu-west-1
spring.cloud.aws.sqs.endpoint=http://localhost:4566

# SQS consumer
aws.sqs.consumer.event-notifications.enabled=true
aws.sqs.consumer.event-notifications.queue-name=event_notifications_sqs
aws.sqs.consumer.event-notifications.dlq-name=event_notifications_sqs_dlq

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# Security
api.security.key=cobre-dev-api-key

# Logging
logging.level.org.hibernate.orm.connections.pooling=warn
